### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by romseguy** [nolanlawson/async-functions-in-pouchdb#1]
Did a fresh clone, npm install and:

$ npm run build

> async-functions-in-pouchdb@1.0.0 build /home/romain/web/learn/async-functions-in-pouchdb
> mkdir -p dist && node ./bin/build.js && npm run min

Error : Cannot find module 'es3ify' from '/home/romain/web/learn/async-functions-in-pouchdb/node_modules/babel-runtime'

> async-functions-in-pouchdb@1.0.0 min /home/romain/web/learn/async-functions-in-pouchdb
> uglifyjs dist/async-functions-in-pouchdb.js -mc > dist/async-functions-in-pouchdb.min.js

util.print: Use console.log instead

**Comment by nolanlawson** [comment]
sorry, let me know if that fixes it
